//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\work\binary\learn\ANTLR\BSA14-ANTLR\Calculator\Calc.Antlr\Calc.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace CalculatorV2.Parser.Calc.Antlr {
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class CalcParser : Parser {
	public const int
		WS=1, LP=2, RP=3, ZERO=4, FLOAT=5, OP_PR1=6, OP_SUM=7, OP_DIV=8, OP_MUL=9;
	public static readonly string[] tokenNames = {
		"<INVALID>", "WS", "'('", "')'", "ZERO", "FLOAT", "OP_PR1", "OP_SUM", 
		"'/'", "'*'"
	};
	public const int
		RULE_expr = 0, RULE_zero_value = 1, RULE_value = 2, RULE_entry = 3;
	public static readonly string[] ruleNames = {
		"expr", "zero_value", "value", "entry"
	};

	public override string GrammarFileName { get { return "Calc.g4"; } }

	public override string[] TokenNames { get { return tokenNames; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }


	private void zeroDetected()
	{
	    throw new System.InvalidOperationException("division by zero");
	}

	public CalcParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberContext : ExprContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public Zero_valueContext zero_value() {
			return GetRuleContext<Zero_valueContext>(0);
		}
		public NumberContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterNumber(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitNumber(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParensContext : ExprContext {
		public ITerminalNode RP() { return GetToken(CalcParser.RP, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode LP() { return GetToken(CalcParser.LP, 0); }
		public ParensContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterParens(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitParens(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParens(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryOperationContext : ExprContext {
		public ITerminalNode OP_DIV() { return GetToken(CalcParser.OP_DIV, 0); }
		public IReadOnlyList<ExprContext> expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ITerminalNode OP_PR1() { return GetToken(CalcParser.OP_PR1, 0); }
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode OP_SUM() { return GetToken(CalcParser.OP_SUM, 0); }
		public Zero_valueContext zero_value() {
			return GetRuleContext<Zero_valueContext>(0);
		}
		public BinaryOperationContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterBinaryOperation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitBinaryOperation(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(_ctx, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 0;
		EnterRecursionRule(_localctx, 0, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 15;
			switch ( Interpreter.AdaptivePredict(_input,0,_ctx) ) {
			case 1:
				{
				_localctx = new NumberContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;

				State = 9; zero_value();
				}
				break;

			case 2:
				{
				_localctx = new NumberContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 10; value();
				}
				break;

			case 3:
				{
				_localctx = new ParensContext(_localctx);
				_ctx = _localctx;
				_prevctx = _localctx;
				State = 11; Match(LP);
				State = 12; expr(0);
				State = 13; Match(RP);
				}
				break;
			}
			_ctx.stop = _input.Lt(-1);
			State = 30;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,2,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 28;
					switch ( Interpreter.AdaptivePredict(_input,1,_ctx) ) {
					case 1:
						{
						_localctx = new BinaryOperationContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 17;
						if (!(Precpred(_ctx, 5))) throw new FailedPredicateException(this, "Precpred(_ctx, 5)");
						State = 18; Match(OP_PR1);
						State = 19; expr(6);
						}
						break;

					case 2:
						{
						_localctx = new BinaryOperationContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 20;
						if (!(Precpred(_ctx, 4))) throw new FailedPredicateException(this, "Precpred(_ctx, 4)");
						State = 21; Match(OP_SUM);
						State = 22; expr(5);
						}
						break;

					case 3:
						{
						_localctx = new BinaryOperationContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 23;
						if (!(Precpred(_ctx, 6))) throw new FailedPredicateException(this, "Precpred(_ctx, 6)");
						State = 24; Match(OP_DIV);
						State = 25; zero_value();
						 zeroDetected(); 
						}
						break;
					}
					} 
				}
				State = 32;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,2,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Zero_valueContext : ParserRuleContext {
		public ITerminalNode ZERO() { return GetToken(CalcParser.ZERO, 0); }
		public ITerminalNode OP_SUM() { return GetToken(CalcParser.OP_SUM, 0); }
		public Zero_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_zero_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterZero_value(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitZero_value(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitZero_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Zero_valueContext zero_value() {
		Zero_valueContext _localctx = new Zero_valueContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_zero_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			_la = _input.La(1);
			if (_la==OP_SUM) {
				{
				State = 33; Match(OP_SUM);
				}
			}

			State = 36; Match(ZERO);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ITerminalNode OP_SUM() { return GetToken(CalcParser.OP_SUM, 0); }
		public ITerminalNode FLOAT() { return GetToken(CalcParser.FLOAT, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39;
			_la = _input.La(1);
			if (_la==OP_SUM) {
				{
				State = 38; Match(OP_SUM);
				}
			}

			State = 41; Match(FLOAT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntryContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(CalcParser.Eof, 0); }
		public EntryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entry; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterEntry(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitEntry(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntry(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EntryContext entry() {
		EntryContext _localctx = new EntryContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_entry);
		try {
			State = 45;
			switch (_input.La(1)) {
			case LP:
			case ZERO:
			case FLOAT:
			case OP_SUM:
				EnterOuterAlt(_localctx, 1);
				{
				State = 43; expr(0);
				}
				break;
			case Eof:
				EnterOuterAlt(_localctx, 2);
				{
				State = 44; Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 0: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(_ctx, 5);

		case 1: return Precpred(_ctx, 4);

		case 2: return Precpred(_ctx, 6);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\v\x32\x4\x2\t\x2"+
		"\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2"+
		"\x3\x2\x5\x2\x12\n\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2"+
		"\x3\x2\x3\x2\x3\x2\a\x2\x1F\n\x2\f\x2\xE\x2\"\v\x2\x3\x3\x5\x3%\n\x3\x3"+
		"\x3\x3\x3\x3\x4\x5\x4*\n\x4\x3\x4\x3\x4\x3\x5\x3\x5\x5\x5\x30\n\x5\x3"+
		"\x5\x2\x2\x3\x2\x6\x2\x2\x4\x2\x6\x2\b\x2\x2\x2\x35\x2\x11\x3\x2\x2\x2"+
		"\x4$\x3\x2\x2\x2\x6)\x3\x2\x2\x2\b/\x3\x2\x2\x2\n\v\b\x2\x1\x2\v\x12\x5"+
		"\x4\x3\x2\f\x12\x5\x6\x4\x2\r\xE\a\x4\x2\x2\xE\xF\x5\x2\x2\x2\xF\x10\a"+
		"\x5\x2\x2\x10\x12\x3\x2\x2\x2\x11\n\x3\x2\x2\x2\x11\f\x3\x2\x2\x2\x11"+
		"\r\x3\x2\x2\x2\x12 \x3\x2\x2\x2\x13\x14\f\a\x2\x2\x14\x15\a\b\x2\x2\x15"+
		"\x1F\x5\x2\x2\b\x16\x17\f\x6\x2\x2\x17\x18\a\t\x2\x2\x18\x1F\x5\x2\x2"+
		"\a\x19\x1A\f\b\x2\x2\x1A\x1B\a\n\x2\x2\x1B\x1C\x5\x4\x3\x2\x1C\x1D\b\x2"+
		"\x1\x2\x1D\x1F\x3\x2\x2\x2\x1E\x13\x3\x2\x2\x2\x1E\x16\x3\x2\x2\x2\x1E"+
		"\x19\x3\x2\x2\x2\x1F\"\x3\x2\x2\x2 \x1E\x3\x2\x2\x2 !\x3\x2\x2\x2!\x3"+
		"\x3\x2\x2\x2\" \x3\x2\x2\x2#%\a\t\x2\x2$#\x3\x2\x2\x2$%\x3\x2\x2\x2%&"+
		"\x3\x2\x2\x2&\'\a\x6\x2\x2\'\x5\x3\x2\x2\x2(*\a\t\x2\x2)(\x3\x2\x2\x2"+
		")*\x3\x2\x2\x2*+\x3\x2\x2\x2+,\a\a\x2\x2,\a\x3\x2\x2\x2-\x30\x5\x2\x2"+
		"\x2.\x30\a\x2\x2\x3/-\x3\x2\x2\x2/.\x3\x2\x2\x2\x30\t\x3\x2\x2\x2\b\x11"+
		"\x1E $)/";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace CalculatorV2.Parser.Calc.Antlr
